services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  MB\Angelshop\:
    resource: '../Classes/*'

  MB\Angelshop\PageTitle\AngelshopPageTitleProvider:
    public: true

  Symfony\Component\Translation\Command\XliffLintCommand:
    arguments:
      $requireStrictFileNames: false
    tags:
      - name: console.command
        command: 'lint:xliff'

  MB\Angelshop\EventListener\PageModulePreviewEventListener:
    tags:
      - name: event.listener
        identifier: page-properties-to-page-module

  MB\Angelshop\EventListener\AngelshopPreviewRendererEventListener:
    tags:
      - name: event.listener
        identifier: 'angelshop/preview-renderer'

imports:
  - { resource: Backend/DashboardWidgets.yaml }
