services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MB\Angelshop\:
    resource: '../Classes/*'

  Symfony\Component\Translation\Command\XliffLintCommand:
    arguments:
      $requireStrictFileNames: false
    tags:
      - name: 'console.command'
        command: 'lint:xliff'
  Symfony\Component\Yaml\Command\LintCommand:
    arguments:
      $name: 'Yaml Linter'
    tags:
      - name: 'console.command'
        command: 'lint:yaml'

imports:
  - { resource: Backend/DashboardWidgets.yaml }
