<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "angelshop"
 * Auto generated by Extension Builder 2016-05-28
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'angelshop',
    'description' => 'Extension with Bootstrap Modern Business Theme',
    'category' => 'Provider Extension',
    'author' => 'Michael Blunck',
    'author_email' => 'mi.blunck@gmail.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '7.6.0-8.9.99',
            'vhs' => '3.0.0-4.1.0',
            'formhandler' => '2.3.1-2.4.99',
            'direct_mail' => '5.1.0-5.2.99',
            'tt_address' => '3.2.1',
            'sourceopt' => '0.9.3-1.0.0',
            'news' => '6.0.0 - 6.99.99'
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
);