<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "angelshop"
 * Auto generated by Extension Builder 2016-05-28
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['angelshop'] = [
    'title' => 'angelshop',
    'description' => 'Extension with Bootstrap Modern Business Theme',
    'category' => 'Provider Extension',
    'author' => 'Michael Blunck',
    'author_email' => 'mi.blunck@gmail.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-10.9.99',
            'news' => '7.2.0-10.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
