#!/bin/bash

## Description: Run TYPO3 CLI (ecs) command inside the web container
## Usage: grunt [args]
## Example: "ddev ecs site:list" or "ddev ecs list" or "ddev ecs extension:list"
## ProjectTypes: typo3
## ExecRaw: true

cd frontend/
grunt "$@"
