config.disableAllHeaderCode = 1
mod.web_modules.dmail.from_email=info@aba-angelshop.de
mod.web_modules.dmail.from_name= ABA Angelshop
mod.web_modules.dmail.replyto_email= info@aba-angelshop.de
mod.web_modules.dmail.replyto_name= ABA-Angelshop
mod.web_modules.dmail.priority=3
mod.web_modules.dmail.sendOptions=2
mod.web_modules.dmail.includeMedia=1
mod.web_modules.dmail.flowedFormat=0
mod.web_modules.dmail.plainParams=&type=99
mod.web_modules.dmail.use_domain=0
mod.web_modules.dmail.quick_mail_encoding=quoted-printable
mod.web_modules.dmail.direct_mail_encoding=quoted-printable
mod.web_modules.dmail.quick_mail_charset=utf-8
mod.web_modules.dmail.direct_mail_charset=iso-8859-1
mod.web_modules.dmail.use_rdct=0
mod.web_modules.dmail.long_link_mode=0
mod.web_modules.dmail.enable_jump_url=0
mod.web_modules.dmail.jumpurl_tracking_privacy=0
mod.web_modules.dmail.enable_mailto_jump_url=0
